.TH "GH\-ANNOTATE" "1" "September 2015" "" ""
.SH "NAME"
\fBgh-annotate\fR \- Add GitHub links to Markdown files
.SH USAGE
.P
gh\-annotate \fIfile\fR
.br
\|\.\.\. | gh\-annotate > \fIoutfile\fR
.SH DESCRIPTION
.P
Adds GitHub links to Markdown files\. Perfect for maintaining changelog files and other Markdown artifacts\.
.P
Running gh\-annotate(1) on a file will perform the following things:
.RS 0
.IP \(bu 2
Turns \fB#847\fP to issue links\.
.IP \(bu 2
Turns \fB@rstacruz\fP to user links\.
.IP \(bu 2
Turns \fBv0\.2\.4(\.\.\.v0\.2\.3)\fP into compare links\.

.RE
.P
It Is idempotent, so running (and re\-running) it on a file should have no side effects\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fIfile\fR
.br
The file to operate on\. If provided, it will be written to in place\.
.IP \(bu 2
\fB\-h\fP, \fB\-\-help\fP
.br
Displays the help screen\.
.IP \(bu 2
\fB\-\-version\fP
.br
Displays version information\.

.RE
.SH INSTALLATION
.P
gh\-annotate(1) is available via npm as gh\-annotate \fIhttps://npmjs\.org/package/gh\-annotate\fR\|\.
.P
.RS 2
.nf
npm install \-g gh\-annotate
.fi
.RE
.SH EXAMPLE
.P
Given this file:
.P
.RS 2
.nf
$ cat CHANGELOG\.md

  ## v0\.8\.2

  * Fix blabberdupes (@manilajs, #2)
  * Improve dapperdonks (@mashupgarage, #8)
.fi
.RE
.P
Run it, and you get this:
.P
.RS 2
.nf
$ gh\-annotate CHANGELOG\.md
$ cat CHANGELOG\.md

## v0\.8\.2

* Fix blabberdupes ([@manilajs], [#2])
* Improve dapperdonks ([@mashupgarage], [#8])

[@manilajs]: https://github\.com/manilajs
[@mashupgarage]: https://github\.com/mashupgarage
[#2]: https://github\.com/rstacruz/jquery\.transit/issues/2
[#8]: https://github\.com/rstacruz/jquery\.transit/issues/8
.fi
.RE
.SH COPYRIGHT
.P
\fBgh\-annotate\fR (c) 2015+, Rico Sta\. Cruz\. Released under the MIT License\.
Authored and maintained by Rico Sta\. Cruz with help from contributors\.
.RS 0
.IP \(bu 2
ricostacruz\.com \fIhttp://ricostacruz\.com\fR
.IP \(bu 2
GitHub rstacruz/gh\-annotate \fIhttps://github\.com/rstacruz/gh\-annotate\fR
.IP \(bu 2
GitHub @rstacruz \fIhttps://github\.com/rstacruz\fR
.IP \(bu 2
Twitter @rstacruz \fIhttps://twitter\.com/rstacruz\fR

.RE

